name: Compatibility Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        filament: ['^3.0', '^4.0']

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - run: composer install

      - run: composer require filament/filament:${{ matrix.filament }} --no-update

      - run: composer update

      - run: vendor/bin/pest